# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Shubham Maurya'
tagline:             'Personal Blog'
description:         'Currently testing <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer.'
url:                 http://mastershubham.github.io
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              Shubham Maurya
  url:               https://twitter.com/mastershubhamx
  email:             mastershubham420@gmail.com

# Custom vars
version:             'I dont Know'
