# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Just a test blog'
tagline:             'Personal Blog'
description:         'Currently testing <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer.'
url:                 www.google.com
baseurl:             ''
paginate:            2

# About/contact
author:
  name:              Test McTest
  url:               https://twitter.com/test
  email:             test@gmail.com

# Custom vars
version:             '1.0'
