# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Focus on the objective' 
tagline:             'Egils blog'
description:         'Blog about Machine Learning, data science and stuff.'
url:                 www.google.com
baseurl:             ''
paginate:            2 

# About/contact
author:
  name:              Test McTest
  url:               https://twitter.com/test
  email:             test@gmail.com

# Custom vars
